spring:
  datasource:
    url: jdbc:mysql://192.168.0.2:3306/foodie-shop-prod?serverTimezone=GMT%2b8
    password: proaim@2020
  redis:
    host: 192.168.0.2
    port: 6379
    password: proaim@2020
    database: 2