############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
  # Spring Boot Tomcat配置详解：https://www.cnblogs.com/javastack/p/9153952.html
  tomcat:
    uri-encoding: UTF-8
    basedir: "logs/@artifactId@/tomcat"
    accesslog:
      enabled: true
      directory: "logs"
      encoding: utf-8
      file-date-format: _yyyy-MM-dd
      locale: zh_CN
      max-days: 30
      prefix: "tomcat_access_log"
      suffix: ".log"
      pattern: "[${spring.application.name}] ===> 请求时间-%t 客户端IP-%a 客户端Host-%h
            客户端协议-%H 线程名称-%I SessionId-%S 请求URL-%U 请求方法-%m 请求状态码-%s 耗时(ms)-%D 连接状态-%X"
  max-http-header-size: 80KB
  # 开启优雅停止 Web 容器，默认为 IMMEDIATE：立即停止
  shutdown: graceful

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  lifecycle:
    # 优雅停机-最大等待时间
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev # 默认启动环境
  application:
    #    name: foodie-shop # 应用名称
    name: "@artifactId@" # 应用名称
  datasource:
    type: com.zaxxer.hikari.HikariDataSource      # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql驱动
    #    url: jdbc:mysql://192.168.0.2:3306/foodie-shop-dev?serverTimezone=GMT%2b8
    username: root
    #    password: proaim@2020
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  ## 文件上传 配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 512000          # 文件上传大小限制为500KB
      max-request-size: 512000       # 请求大小限制为500KB
  ## redis
  redis:
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: -1
  ## thymeleaf
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    ## thymeleaf 配置 不再检查 templates 文件夹下是否存在模板。
    check-template: false
    check-template-location: false
#  session:
#    store-type: redis

############################################################
#
# mybatis 配置
#
############################################################
#mybatis:
#  type-aliases-package: cn.myst.web.**.pojo     # 所有POJO类所在包路径
#  mapper-locations: classpath*:mapper/*.xml      # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

## actuator监控指标配置
management:
  endpoints:
    web:
      base-path: /actuator # 配置端点访问前缀
      exposure:
        include: '*' # 以 web方式暴露所有端点
        exclude: info,beans,env #在暴露所有端点的前提下，可以排除某个端点(不暴露)
# 应用健康详细信息
  endpoint:
    health:
      show-details: always