spring:
  datasource:
    url: jdbc:mysql://192.168.100.123:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    password: proaim@2020
  # redis
  redis:
    host: 192.168.0.2
    port: 6379
    password: proaim@2020
    database: 0